import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class TermsAndCondition extends StatefulWidget {
  @override
  _TermsAndConditionState createState() => _TermsAndConditionState();
}

class _TermsAndConditionState extends State<TermsAndCondition> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Terms and Conditions'),
      ),
      body: ListView(
        padding: EdgeInsets.all(35),
        children: <Widget>[
          SizedBox(height: 50),
          Text('Welcome to Daily Needs!',
              style: general.copyWith(fontWeight: FontWeight.w600)),
          SizedBox(height: 40),
          Text(
              'Please read these conditions carefully before using the Daily Needs Application. By using the Daily Needs App, you signify your agreement to be bound by these conditions',
              style: general),
          SizedBox(height: 25),
          Text(
              'In addition, when you use any current or future Daily Needs service, you will also be subject to the terms, guidelines and conditions applicable to that Daily Needs Service. If these Conditions of Use are inconsistent with such Terms, the Terms will control.',
              style: general),
          SizedBox(height: 25),
          Text(
              'These "Conditions of Use" constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.',
              style: general),
//
          SizedBox(height: 25),
          Text(
            'Conditions Relating to Your Use of Daily Needs',
            style: TextStyle(
                fontWeight: FontWeight.w600, fontSize: 17, height: 1.3),
          ),
          SizedBox(height: 15),
          Text(
            'Daily Needs is always conscious about the quality and safety of the product delivered to the customer, because of which the sourcing  of products are done in a careful manner. However Daily Needs will not be responsible or liable for any difficulty faced by the customer due to the quality of product provided by the seller.',
            style: general,
          ),
          SizedBox(height: 60),
          Text('Revised: July 12, 2020')
        ],
      ),
    );
  }
}

const TextStyle general =
    TextStyle(fontSize: 16, wordSpacing: 1.5, letterSpacing: 0.8, height: 1.3);
