name: daily_needs
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.1+11

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  carousel_slider: ^2.2.1
  shared_preferences: ^0.5.7
  provider: ^4.1.2
  firebase_core: ^0.5.2+1
  cloud_firestore: ^0.14.3+1
  firebase_auth: ^0.18.3+1
  modal_progress_hud: ^0.1.3
  intl: ^0.16.1
  rflutter_alert: ^1.0.3
  http: ^0.12.1
  geolocator: ^5.3.1
  permission_handler: ^5.0.0+hotfix.6
  app_settings: ^4.0.0
  auto_size_text: ^2.1.0
  google_fonts: ^1.1.0
  firebase_messaging: ^7.0.3
  cached_network_image: ^2.2.0+1
  flutter_spinkit: ^4.1.2+1
  url_launcher: ^5.5.0
  percent_indicator: ^2.1.3
  in_app_update: ^1.1.11
  transparent_image: ^1.0.0
  fluttertoast: ^4.0.0
  flutter_staggered_animations: ^0.1.2
  connectivity: ^0.4.8+6
  flutter_typeahead: ^1.8.7
  flutter_swiper: ^1.1.6
  animated_icon_button: ^0.3.0
  razorpay_flutter: ^1.2.2
  country_pickers: ^1.3.0
  pin_entry_text_field: ^0.1.4
  argon_buttons_flutter: ^1.0.6
  google_maps_flutter: ^0.5.28
  timezone: ^0.5.7
  flare_flutter: ^2.0.6
  splashscreen: ^1.3.5





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/chicken/
    - assets/fish/
    - assets/beef/
    - assets/mutton/
    - assets/vegetables/
    - assets/fish/sailFish/
    - assets/fish/yellowfinTuna/
    - assets/fish/kingFish/
    - assets/fish/swordFish/
    - assets/bakery/cakes/
    - assets/fish/anchovy/
    - assets/fish/mahi mahi/
    - assets/fish/squid/
    - assets/fish/marlin/
    - assets/fish/sardine/
    - assets/Restaurants/
    - assets/grocery/
    - assets/grocery/1/
    - assets/grocery/pulses/
    - assets/grocery/waste/
    - assets/flare/
