List<Map> ammmumaKitchen = [
  {
    'name': 'Plate Shavarma',
    'isAvailable': true,
    'openHour': 15,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FBlack%20bowl%2Fshawarma%20plate-min.jpg?alt=media&token=5a1433c6-8094-4a46-9537-8ecdb2d4f8e6',
    'imageType': 'online',
    'isVeg': false,
    'amount': 80,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Roll Shavarma ',
    'isAvailable': true,
    'openHour': 15,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FBlack%20bowl%2Fshawarma%20roll-min.jpg?alt=media&token=ad4526c3-086c-4702-a03b-147a10a093cd',
    'imageType': 'online',
    'isVeg': false,
    'amount': 50,
    'quantity': 1,
    'unit': '',
  },

  // {
  //   'name': 'Kizhi  Biriyani  Chicken',
  //   'desc':
  //       'Two piece chicken, Egg ,Kizhi Biriyani \n(delivery may be delayed)',
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2FKIZHI%20chicken%20BIRIYANI%20with%20egg.jpg?alt=media&token=c48afe97-c310-4cf1-95a5-749aa327c838',
  //   'imageType': 'online',
  //   'isVeg': false,
  //   'category': 'Kizhi',
  //   'amount': 140,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Pothi Biriyani Chicken',
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2Fpothi%20biriyani%20chicken.jpg?alt=media&token=9e271b62-99f3-4163-b7d4-c6cc961cb1d1',
  //   'desc': 'Two piece chicken ,Pothi Biriyani \n(delivery may be delayed)',
  //   'imageType': 'online',
  //   'isVeg': false,
  //   'category': "Pothi",
  //   'amount': 120,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Ghee Rice',
  //   'isAvailable': true,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FCoconut%20Groves%2FBiriyani%2Fghee%20Rice~1.jpg?alt=media&token=1b00d880-06b1-477c-9fd3-4d9e77168f73',
  //   'imageType': 'online',
  //   'isVeg': true,
  //   'amount': 70,
  //   'quantity': 1,
  //   'unit': '',
  // },

  {
    'name': 'Roll Poratta Beef',
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2FRollporotta-min.jpg?alt=media&token=22b512e5-1bcb-4f61-af67-f512c9dd01ff',
    'desc': 'Roll Poratta - Beef  \n(delivery may be delayed)',
    'imageType': 'online',
    'isVeg': false,
    'category': "",
    'amount': 40,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Roll Poratta Chicken',
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2FRollporotta-min.jpg?alt=media&token=22b512e5-1bcb-4f61-af67-f512c9dd01ff',
    'desc': 'Roll Poratta - Chicken  \n(delivery may be delayed)',
    'imageType': 'online',
    'isVeg': false,
    'category': "",
    'amount': 40,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Roll Poratta Veg',
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2FRollporotta-min.jpg?alt=media&token=22b512e5-1bcb-4f61-af67-f512c9dd01ff',
    'desc': 'Roll Poratta - Vegetables  \n(delivery may be delayed)',
    'imageType': 'online',
    'isVeg': false,
    'category': "",
    'amount': 40,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Mughlai Paratha Veg',
    'isAvailable': true,
    'desc': ' \n(delivery may be delayed)',
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2FMughali%2FVeg%20Mughlai%20Paratha.jpg?alt=media&token=c80dc145-4b01-47d6-b1b0-abd55977dc3a',
    'imageType': 'online',
    'isVeg': true,
    'category': "Mughlai",
    'amount': 100,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Mughlai Paratha Egg',
    'isAvailable': true,
    'desc': ' \n(delivery may be delayed)',
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2FMughali%2FMughlai%20Egg%20Paratha~1.jpg?alt=media&token=9f3147db-42e1-41ac-9316-5b6aba693247',
    'imageType': 'online',
    'isVeg': false,
    'category': "Mughlai",
    'amount': 100,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Mughlai Paratha Chicken',
    'isAvailable': true,
    'desc': ' \n(delivery may be delayed)',
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2FMughali%2FMughlai%20Kheema%20Paratha%20Chicken.jpg?alt=media&token=3e34c8f9-52ea-4f55-b792-3424cdf4eb91',
    'imageType': 'online',
    'isVeg': false,
    'category': "Mughlai",
    'amount': 100,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Mughlai Paratha Beef',
    'isAvailable': true,
    'desc': ' \n(delivery may be delayed)',
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2FMughali%2FBeeg%20Mughali%20porotta.jpg?alt=media&token=e83d6dd0-5e23-456d-ad97-64ecf7ad2aab',
    'imageType': 'online',
    'isVeg': false,
    'category': "Mughlai",
    'amount': 100,
    'quantity': 1,
    'unit': '',
  },
  // {
  //   'name': 'Beef Kizhi Biriyani',
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2Fbeef%20kizhi%20biriyani.jpg?alt=media&token=bef68ae2-d0a4-4426-82d8-26ffcc5ec3ce',
  //   'desc': '',
  //   'imageType': 'online',
  //   'isVeg': false,
  //   'category': "Kizhi",
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': 'kg',
  // },
  {
    'name': 'Kizhi Poratta Beef ',
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2Fbeef%20kizhi%20porotta~2.jpg?alt=media&token=d71b1cca-4acc-44cd-8156-959a3855dbe0',
    'desc': 'Kizhi Poratta -Beef  \n(delivery may be delayed)',
    'imageType': 'online',
    'isVeg': false,
    'category': "Kizhi",
    'amount': 70,
    'quantity': 1,
    'unit': '',
  },
  // {
  //   'name': 'Kizhi Chicken Poratta',
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2Fkizhi%20chicken%20porotta~1.jpg?alt=media&token=54012568-bb34-4737-999a-f077a0477faf',
  //   'desc': '',
  //   'imageType': 'online',
  //   'isVeg': false,
  //   'category': "Kizhi",
  //   'amount': 80,
  //   'quantity': 1,
  //   'unit': 'kg',
  // },
  // {
  //   'name': 'Kada Biriyani',
  //   'isAvailable': false,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2Fkada.jpg?alt=media&token=bbce32d5-3342-4515-a2f3-7c6b6e78252c',
  //   'desc': 'SUNDAY SPECIAL ..!! ',
  //   //     ഓർഡർ ഉച്ചക്ക് 11 മണി വരെ മാത്രം സ്വീകരിക്കുന്നു',
  //   'imageType': 'online',
  //   'isVeg': false,
  //   // 'category': "Kizhi",
  //   'amount': 140,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Beef Biriyani',
  //   'isAvailable': false,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fammoomas%20kitchen%2FbeefBiriyani-min.jpg?alt=media&token=39bb94fd-5a3e-40f8-bbb1-463d2d4c3324',
  //   'desc': 'SUNDAY SPECIAL ..!!',
  //   'imageType': 'online',
  //   'isVeg': false,
  //   // 'category': "Kizhi",
  //   'amount': 125,
  //   'quantity': 1,
  //   'unit': '',
  // },
];
