List<Map> coconut = [
  {
    'name': 'Chicken Biriyani',
    'isAvailable': true,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FCoconut%20Groves%2FBiriyani%2Fchicken%20biryani~1.jpg?alt=media&token=0715014a-f2e4-43ef-951b-74e74e2037d2',
    'imageType': 'online',
    'isVeg': false,
    'amount': 130,
    'quantity': 1,
    'unit': '',
    'category': "Biriyani",
  },
  // {
  //   'name': 'Beef Biriyani',
  //   'isAvailable': false,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FCoconut%20Groves%2FBiriyani%2FBeef%20%20biryani%203~1.jpg?alt=media&token=3bea9c8c-c330-4108-9cac-3d3e74082185',
  //   'imageType': 'online',
  //   'isVeg': false,
  //   'amount': 130,
  //   'quantity': 1,
  //   'unit': '',
  //   'category': "Biriyani",
  // },
  // {
  //   'name': 'Ghee Rice',
  //   'isAvailable': true,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FCoconut%20Groves%2FBiriyani%2Fghee%20Rice~1.jpg?alt=media&token=1b00d880-06b1-477c-9fd3-4d9e77168f73',
  //   'imageType': 'online',
  //   'isVeg': true,
  //   'amount': 80,
  //   'quantity': 1,
  //   'unit': '',
  // },
  {
    'name': 'Fried Rice Chicken',
    'isAvailable': true,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FCoconut%20Groves%2FBiriyani%2FChicken-Fried-Rice~1.jpg?alt=media&token=1445eaad-e5be-4d60-9a9c-60e8b5eafda0',
    'imageType': 'online',
    'isVeg': false,
    'amount': 120,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Fried Rice Egg',
    'isAvailable': true,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FCoconut%20Groves%2FBiriyani%2FEgg-Fried-Rice-3~1.jpg?alt=media&token=c263d954-8c37-4251-8c8a-fa86ff5c8f9a',
    'imageType': 'online',
    'isVeg': true,
    'amount': 100,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Fried Rice Veg',
    'isAvailable': true,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FCoconut%20Groves%2FBiriyani%2FVegetable-Fried-Rice-3~1.jpg?alt=media&token=ce7cff1f-3ff4-415d-9d92-686fafb866ee',
    'imageType': 'online',
    'isVeg': true,
    'amount': 90,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Thandoori Alfaham',
    'openHour': 16,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Falfaham%2Ftandoori.jpg?alt=media&token=b14f6a14-3e71-47a2-b4ea-83d1cb5f3dc9',
    'imageType': 'online',
    'types': [
      {'type': 'Full', 'amount': 430, 'quantity': 1},
      {'type': 'Half', 'amount': 230, 'quantity': 1},
      {'type': 'Qt.', 'amount': 115, 'quantity': 1},
    ],
    'isVeg': false,
    'category': "Alfaham",
    'amount': 160,
    'quantity': 1,
    'unit': '',
    'isAvailable': true,
  },
  // {
  //   'name': 'Green Chilly Alfaham',
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Falfaham%2Fkondattam.jpg?alt=media&token=da5aaabd-db20-48f7-b599-bf79090e0e55',
  //   'imageType': 'online',
  //   'isVeg': false,
  //   'category': "Alfaham",
  //   'openHour': 16,
  //   'types': [
  //     {'type': 'Full', 'amount': 450, 'quantity': 1},
  //     {'type': 'Half', 'amount': 240, 'quantity': 1},
  //     {'type': 'Qt.', 'amount': 120, 'quantity': 1},
  //   ],
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  // },
  {
    'name': 'Pepper Alfaham',
    'openHour': 16,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Falfaham%2Fpepper.png?alt=media&token=623d04ef-638e-4f47-b88d-1a5cf664046a',
    'isVeg': false,
    'imageType': 'online',
    'types': [
      {'type': 'Full', 'amount': 450, 'quantity': 1},
      {'type': 'Half', 'amount': 240, 'quantity': 1},
      {'type': 'Qt.', 'amount': 120, 'quantity': 1},
    ],
    'category': "Alfaham",
    'amount': 160,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Porotta',
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FBlack%20bowl%2FPOROTTA.jpg?alt=media&token=2504638f-5849-4ba8-a831-3dba320a8d62',
    'imageType': 'online',
    'isVeg': true,
    'category': "Add On",
    'amount': 10,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Kuboos',
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FBlack%20bowl%2Fkuboos.jpg?alt=media&token=0ffb265b-b7e8-47a1-a212-7276ea19dd55',
    'imageType': 'online',
    'isVeg': true,
    'category': "Add On",
    'amount': 10,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Mayonnaise',
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FCoconut%20Groves%2FHomemade-Mayonnaise.jpg?alt=media&token=aa749e94-e71e-484c-a193-af5b64d5ca31',
    'imageType': 'online',
    'isVeg': true,
    'category': "Add On",
    'amount': 20,
    'quantity': 1,
    'unit': '',
  },
];
