List<Map> vkp = [
  // {
  //   'name': 'Tandoori Chicken Pizza',
  //   'isVeg': false,
  //   'types': [
  //     {'type': 'Small', 'amount': 190, 'quantity': 1},
  //     {'type': 'Medium', 'amount': 250, 'quantity': 1},
  //     // {'type': 'Large', 'amount': 330, 'quantity': 1}
  //   ],
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpizza%2Fpepper-delight-tandoori-chicken-pizza-3-min.jpg?alt=media&token=b43818b2-cb3a-45ee-bcd6-59552ef2ffed',
  //   'desc': 'Onion, Red Capsicum, Green Chilly,Tandoori Chicken, Cheese',
  //   'imageType': 'online',
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  //   'category': 'Pizza',
  //   'isAvailable': false,
  // },
  // {
  //   'name': 'BBQ Chicken',
  //   'openHour': 12,
  //   'isVeg': false,
  //   'types': [
  //     {'type': 'Small', 'amount': 200, 'quantity': 1},
  //     {'type': 'Medium', 'amount': 270, 'quantity': 1},
  //     // {'type': 'Large', 'amount': 350, 'quantity': 1}
  //   ],
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpizza%2Fbbq%20chiken%20pizza.jpg?alt=media&token=7d79f46e-5d26-46a7-9a05-a306e0a8d54f',
  //   'imageType': 'online',
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  //   'desc': 'Onion, Green Chilly, BBQ Chicken, Cheese',
  //   'category': 'Pizza',
  //   'isAvailable': false,
  // },
  // {
  //   'name': 'Peri Peri Chicken',
  //   'openHour': 12,
  //   'isVeg': false,
  //   'types': [
  //     {'type': 'Small', 'amount': 220, 'quantity': 1},
  //     {'type': 'Medium', 'amount': 280, 'quantity': 1},
  //     // {'type': 'Large', 'amount': 360, 'quantity': 1}
  //   ],
  //   'desc': 'Onion, Green Chilly, Tomato, Cheese & Peri Peri Chicken',
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpizza%2Fperi%20peri.jpg?alt=media&token=1f7e3796-4627-4fa3-a9eb-4f50aade82ef',
  //   'imageType': 'online',
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  //   'category': 'Pizza',
  //   'isAvailable': false,
  // },
  // {
  //   'name': 'Margarita',
  //   'isVeg': false,
  //   'openHour': 12,
  //   'types': [
  //     {'type': 'Small', 'amount': 150, 'quantity': 1},
  //     {'type': 'Medium', 'amount': 210, 'quantity': 1},
  //     // {'type': 'Large', 'amount': 290, 'quantity': 1}
  //   ],
  //   'desc': 'Cheese, Sauce',
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpizza%2Fmargherita-pizza.jpg?alt=media&token=6d9c1183-2387-4f2c-9d43-76a6207f2ca3',
  //   'imageType': 'online',
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  //   'category': 'Pizza',
  //   'isAvailable': false,
  // },
  // {
  //   'name': 'Tandoori Veg',
  //   'isVeg': true,
  //   'openHour': 12,
  //   'types': [
  //     {'type': 'Small', 'amount': 160, 'quantity': 1},
  //     {'type': 'Medium', 'amount': 220, 'quantity': 1},
  //     // {'type': 'Large', 'amount': 260, 'quantity': 1}
  //   ],
  //   'desc': 'Paneer, Onion, Capsicum, Green Chilly, Tomato & Cheese',
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpizza%2FIndianTandoori%20veg.jpg?alt=media&token=b86e5c54-610f-45ec-8058-e09178a0ba17',
  //   'imageType': 'online',
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  //   'category': 'Pizza',
  //   'isAvailable': false,
  // },
  // {
  //   'name': 'White Sauce Penne: Veg',
  //   'isVeg': true,
  //   'openHour': 12,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpasta%2Fwhite%20penne%2Fwhte%20penne%20veg.jpg?alt=media&token=fc0f9f3e-6372-4256-8bc0-3cfa618131cd',
  //   'imageType': 'online',
  //   'category': 'Pasta',
  //   'amount': 170,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'White Sauce Penne - Chicken',
  //   'isVeg': false,
  //   'openHour': 12,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpasta%2Fwhite%20penne%2Fwhite%20penne%20chicken.jpg?alt=media&token=f854b3b0-2820-4984-b4c2-1232f01eae02',
  //   'imageType': 'online',
  //   'category': 'Pasta',
  //   'amount': 190,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Red Sauce Penne Veg',
  //   'isVeg': true,
  //   'openHour': 12,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpasta%2Fred%20sause%2Fveg.jpg?alt=media&token=ece1cb1a-9648-4b71-a907-9567675b83cf',
  //   'imageType': 'online',
  //   'category': 'Pasta',
  //   'amount': 170,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Red Sauce Penne Chicken',
  //   'isVeg': false,
  //   'openHour': 12,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpasta%2Fred%20sause%2Fchicken.jpg?alt=media&token=913c5907-ecc3-4523-b8b6-2bdb12792d07',
  //   'imageType': 'online',
  //   'category': 'Pasta',
  //   'amount': 190,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Salsa Rose Veg',
  //   'isVeg': true,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpasta%2Fsalsa%20rose%2FSalsa-Rosa%20veg.jpg?alt=media&token=d3f2aa33-fe59-449b-952a-d0489f3652cd',
  //   'imageType': 'online',
  //   'category': 'Pasta',
  //   'amount': 190,
  //   'quantity': 1,
  //   'unit': 'kg',
  // },
  // {
  //   'name': 'Salsa Rose Chicken',
  //   'isVeg': false,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpasta%2Fsalsa%20rose%2Fnon%20veg.jpg?alt=media&token=bc45331a-05ec-480d-9a82-2f13bbbb21ae',
  //   'imageType': 'online',
  //   'category': 'Pasta',
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Pesto Penne Veg Pasta',
  //   'isVeg': true,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpasta%2Fpesto%20penne%2Fveg.jpg?alt=media&token=e97e5846-5c62-42f7-a3f5-2e186d17b530',
  //   'imageType': 'online',
  //   'category': 'Pasta',
  //   'amount': 190,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Pesto Penne Chicken Pasta',
  //   'isVeg': false,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpasta%2Fpesto%20penne%2Fchik.jpg?alt=media&token=7def0f0a-cdca-4ef2-a117-6f3fde17b635',
  //   'imageType': 'online',
  //   'category': 'Pasta',
  //   'amount': 220,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Baked Chicken Pasta',
  //   'isVeg': false,
  //   'openHour': 12,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fpasta%2Fbaked%20pasta%2Fchik.jfif?alt=media&token=2f5238c7-7346-43f2-96b4-70236d7188b8',
  //   'imageType': 'online',
  //   'category': 'Pasta',
  //   'amount': 240,
  //   'quantity': 1,
  //   'unit': '',
  //   'isAvailable': false
  // },
  // {
  //   'name': 'Chicken Grilled Sandwich',
  //   'isVeg': false,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fsandwich%2Fchicken%20grill.jfif?alt=media&token=a7129933-afb9-4ef4-b52c-d6f404d2a86c',
  //   'imageType': 'online',
  //   'category': 'Sandwich',
  //   'amount': 140,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Chicken Tikka Sandwich',
  //   'isVeg': false,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fsandwich%2Ftikka.jfif?alt=media&token=dcb16525-22f7-487e-be7f-6ff499631842',
  //   'imageType': 'online',
  //   'category': 'Sandwich',
  //   'amount': 150,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Chicken Sandwich',
  //   'isVeg': false,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fsandwich%2Fchiken%20sand.jpg?alt=media&token=1440f8ad-fe1d-4f44-a977-656850658eee',
  //   'imageType': 'online',
  //   'category': 'Sandwich',
  //   'types': [
  //     {'type': 'Indv.', 'amount': 90, 'quantity': 1},
  //     {'type': 'Combo', 'amount': 160, 'quantity': 1},
  //   ],
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Chicken Jumbo Sandwich',
  //   'isVeg': false,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fsandwich%2Fjumbo.jpg?alt=media&token=2cf4b195-6500-404e-a354-6f67ba35fdb6',
  //   'imageType': 'online',
  //   'category': 'Sandwich',
  //   'types': [
  //     {'type': 'Indv.', 'amount': 140, 'quantity': 1},
  //     {'type': 'Combo', 'amount': 200, 'quantity': 1},
  //   ],
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  // },
  {
    'name': 'Bucket Meal',
    'isVeg': false,
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Fbucket%20meal.jpg?alt=media&token=1f484cf5-07fc-49ea-af7f-037d9cadfcd6',
    'imageType': 'online',
    'category': "Vkp's Special",
    'amount': 160,
    'types': [
      {'type': 'Royal - 6Pc', 'amount': 549, 'quantity': 1},
      {'type': 'Family Pack - 9Pc', 'amount': 799, 'quantity': 1},
      {'type': 'Family Spl - 12Pc', 'amount': 1049, 'quantity': 1},
    ],
    'desc':
        '6/9/12 Pc. Chicken, 3/4/6 Garlic Paste, 1/1/2 Coleslaw, 3/4/6 Bun, 1 French Fries',
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Bucket Feast',
    'isVeg': false,
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Fbucket%20feast.jpg?alt=media&token=c19b6baa-3ddd-4610-b9ce-4d67e545237c',
    'imageType': 'online',
    'category': "Vkp's Special",
    'types': [
      {'type': '2 Piece', 'amount': 140, 'quantity': 1},
      {'type': '6 Piece', 'amount': 410, 'quantity': 1},
      {'type': '9 Piece', 'amount': 610, 'quantity': 1},
      {'type': '12 Piece', 'amount': 780, 'quantity': 1},
    ],
    'desc': '2 Piece Chicken Bucket',
    'amount': 160,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Chicken Strips',
    'isVeg': false,
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Fchicken%20strips.jpg?alt=media&token=cd1a846e-ff65-4384-ae5a-caa74ac035d8',
    'imageType': 'online',
    'desc': 'Best Fried 6 Chicken Strips',
    'category': "Vkp's Special",
    'types': [
      {'type': '6 Piece', 'amount': 199, 'quantity': 1},
      {'type': '12 Piece', 'amount': 349, 'quantity': 1},
    ],
    'amount': 160,
    'quantity': 1,
    'unit': 'kg',
  },
  {
    'name': 'Krispy Burger',
    'isAvailable': true,
    'isVeg': false,
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Fkrispy%20burger.jpg?alt=media&token=1af34026-1717-4f87-9077-b88710352549',
    'imageType': 'online',
    'category': "Vkp's Special",
    'desc': 'Fried Crispy Chicken Burger',
    'amount': 160,
    'types': [
      {'type': 'Indv', 'amount': 100, 'quantity': 1},
      {'type': 'Combo', 'amount': 140, 'quantity': 1},
    ],
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'French Fries',
    'isVeg': true,
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Ffrench%20fries.jpg?alt=media&token=6ab6aa57-047e-4528-b6b1-703b4035acb8',
    'imageType': 'online',
    'category': "Vkp's Special",
    'desc': 'Perfect French Potato Fries',
    'types': [
      {'type': 'Small', 'amount': 40, 'quantity': 1},
      {'type': 'Medium', 'amount': 60, 'quantity': 1},
      {'type': 'Large', 'amount': 80, 'quantity': 1},
    ],
    'amount': 160,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Chick Pop',
    'isVeg': false,
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Fpopcorn.jpg?alt=media&token=7a52b3d5-5245-4536-8eac-e0aeead5f0ba',
    'imageType': 'online',
    'category': "Vkp's Special",
    'desc': 'Fried Chicken Popcorn',
    'types': [
      {'type': 'Medium', 'amount': 100, 'quantity': 1},
    ],
    'amount': 160,
    'quantity': 1,
    'unit': '',
  },
  // {
  //   'name': 'Nuggets',
  //   'isVeg': true,
  //   'openHour': 12,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Fnuggets%20veg.gif?alt=media&token=6083145a-f1a2-40bf-910a-f77da602e735',
  //   'imageType': 'online',
  //   'category': "Vkp's Special",
  //   'desc': '',
  //   'types': [
  //     {'type': 'Medium Veg', 'amount': 90, 'quantity': 1},
  //   ],
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  //   'isAvailable': false,
  // },
  // {
  //   'name': 'Nuggets',
  //   'isVeg': false,
  //   'openHour': 12,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2FChicken-Nuggets-1.jpg?alt=media&token=e617b3dd-d3d7-4baa-96ed-9111af304a8e',
  //   'imageType': 'online',
  //   'category': "Vkp's Special",
  //   'amount': 160,
  //   'types': [
  //     {'type': 'Medium Chicken', 'amount': 100, 'quantity': 1},
  //   ],
  //   'quantity': 1,
  //   'unit': '',
  //   'isAvailable': false,
  // },
  // {
  //   'name': 'Long Crispy Burger',
  //   'isAvailable': false,
  //   'isVeg': false,
  //   'openHour': 12,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Flong%20burger.jpg?alt=media&token=c550ddef-18d5-411f-886a-c6743aa5599a',
  //   'imageType': 'online',
  //   'category': "Vkp's Special",
  //   'types': [
  //     {'type': 'Indv', 'amount': 120, 'quantity': 1},
  //     {'type': 'Combo', 'amount': 160, 'quantity': 1},
  //   ],
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  // },
  {
    'name': 'Chicken Warp',
    'isVeg': false,
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Fwarp.jpg?alt=media&token=829d5526-7627-41aa-b620-a83c21f4290a',
    'imageType': 'online',
    'category': "Vkp's Special",
    'amount': 160,
    'types': [
      {'type': 'Indv', 'amount': 120, 'quantity': 1},
      {'type': 'Combo', 'amount': 160, 'quantity': 1},
    ],
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Grill Burger',
    'isAvailable': true,
    'isVeg': false,
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Fgrilled%20burger.jfif?alt=media&token=7fb667d9-3f37-4567-b0b0-c631d85ab3e1',
    'imageType': 'online',
    'category': "Vkp's Special",
    'types': [
      {'type': 'Indv', 'amount': 110, 'quantity': 1},
      {'type': 'Combo', 'amount': 150, 'quantity': 1},
    ],
    'amount': 160,
    'quantity': 1,
    'unit': '',
  },
  // {
  //   'name': 'Longer Grill Burger',
  //   'isAvailable': false,
  //   'isVeg': false,
  //   'openHour': 12,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Flong%20grill%20burger.jpg?alt=media&token=42a3dc85-5095-49a3-b65a-f3b77026557b',
  //   'imageType': 'online',
  //   'category': "Vkp's Special",
  //   'types': [
  //     {'type': 'Indv', 'amount': 110, 'quantity': 1},
  //     {'type': 'Combo', 'amount': 150, 'quantity': 1},
  //   ],
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Beef Burger',
  //   'isVeg': false,
  //   'openHour': 12,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Fbeef%20burger.jpg?alt=media&token=20f878db-1cd0-401f-8989-0494a70d9382',
  //   'imageType': 'online',
  //   'category': "Vkp's Special",
  //   'types': [
  //     {'type': 'Indv', 'amount': 110, 'quantity': 1},
  //     {'type': 'Combo', 'amount': 150, 'quantity': 1},
  //   ],
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  //   'isAvailable': false,
  // },
  {
    'name': 'BBQ Burger',
    'isAvailable': true,
    'isVeg': false,
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Fspecial%2Fbbq%20chicken%20burger.jpg?alt=media&token=197d78da-c74f-4985-964d-22f0d52537b7',
    'imageType': 'online',
    'category': "Vkp's Special",
    'amount': 160,
    'types': [
      {'type': 'Indv', 'amount': 130, 'quantity': 1},
    ],
    'quantity': 1,
    'unit': '',
  },
  // {
  //   'name': 'Alfaham Kondattam',
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Falfaham%2Fkondattam.jpg?alt=media&token=da5aaabd-db20-48f7-b599-bf79090e0e55',
  //   'imageType': 'online',
  //   'isVeg': false,
  //   'openHour': 12,
  //   'category': "Alfaham",
  //   'openHour': 16,
  //   'types': [
  //     {'type': 'Full', 'amount': 400, 'quantity': 1},
  //     {'type': 'Half', 'amount': 200, 'quantity': 1},
  //     {'type': 'Qt.', 'amount': 110, 'quantity': 1},
  //   ],
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Thawa Alfaham',
  //   'isVeg': false,
  //   'openHour': 12,
  //   'openHour': 16,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Falfaham%2Fthawa.jpg?alt=media&token=ee8e9e08-a692-452f-8a61-43964303738b',
  //   'imageType': 'online',
  //   'types': [
  //     {'type': 'Full', 'amount': 400, 'quantity': 1},
  //     {'type': 'Half', 'amount': 200, 'quantity': 1},
  //     {'type': 'Qt.', 'amount': 110, 'quantity': 1},
  //   ],
  //   'category': "Alfaham",
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Pepper Alfaham',
  //   'openHour': 15,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Falfaham%2Fpepper.png?alt=media&token=623d04ef-638e-4f47-b88d-1a5cf664046a',
  //   'isVeg': false,
  //   'openHour': 12,
  //   'imageType': 'online',
  //   'types': [
  //     {'type': 'Full', 'amount': 400, 'quantity': 1},
  //     {'type': 'Half', 'amount': 200, 'quantity': 1},
  //     {'type': 'Qt.', 'amount': 110, 'quantity': 1},
  //   ],
  //   'category': "Alfaham",
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': 'Thandoori Alfaham',
  //   'openHour': 15,
  //   'image':
  //       'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2Fvkp%2Falfaham%2Ftandoori.jpg?alt=media&token=b14f6a14-3e71-47a2-b4ea-83d1cb5f3dc9',
  //   'imageType': 'online',
  //   'types': [
  //     {'type': 'Full', 'amount': 400, 'quantity': 1},
  //     {'type': 'Half', 'amount': 190, 'quantity': 1},
  //     {'type': 'Qt.', 'amount': 100, 'quantity': 1},
  //   ],
  //   'isVeg': false,
  //   'category': "Alfaham",
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': '',
  //   'isAvailable': false,
  // },
  // {
  //   'name': 'Garlic',
  //   'image': '',
  //   'imageType': 'online',
  //   'isVeg': true,
  //   'category': "Add On",
  //   'amount': 10,
  //   'quantity': 1,
  //   'unit': '',
  // },
  // {
  //   'name': '',
  //   'image': '',
  //   'imageType': 'online',
  //   'isVeg': false,
  //   'category': "Vkp's Special",
  //   'amount': 160,
  //   'quantity': 1,
  //   'unit': 'kg',
  // },
  {
    'name': 'Porotta',
    'openHour': 12,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FBlack%20bowl%2FPOROTTA.jpg?alt=media&token=2504638f-5849-4ba8-a831-3dba320a8d62',
    'imageType': 'online',
    'isVeg': true,
    'category': "Add On",
    'amount': 10,
    'quantity': 1,
    'unit': '',
  },
  {
    'name': 'Kuboos',
    'openHour': 15,
    'image':
        'https://firebasestorage.googleapis.com/v0/b/daily-needs-a9c69.appspot.com/o/restaurants%20%2FBlack%20bowl%2Fkuboos.jpg?alt=media&token=0ffb265b-b7e8-47a1-a212-7276ea19dd55',
    'imageType': 'online',
    'isVeg': true,
    'category': "Add On",
    'amount': 10,
    'quantity': 1,
    'unit': '',
  },
];
